# Generated by Django 3.2.7 on 2021-11-27 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NivelEstudios', '0001_initial'),
        ('Aspirante', '0006_alter_aspirante_estadoestudios'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacionProfesional',
            fields=[
                ('idformacionprofesional', models.AutoField(db_column='idFormacionProfesional', primary_key=True, serialize=False)),
                ('centroeducativo', models.CharField(blank=True, db_column='centroEducativo', max_length=100, null=True)),
                ('estadoestudios', models.CharField(blank=True, db_column='estadoEstudios', max_length=50, null=True)),
                ('fechainicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fechacierre', models.DateField(blank=True, db_column='fechaCierre', null=True)),
                ('aspirante_idaspirante', models.ForeignKey(db_column='aspirante_idaspirante', on_delete=django.db.models.deletion.DO_NOTHING, to='Aspirante.aspirante')),
                ('nivelestudios_idnivelestudios', models.ForeignKey(db_column='NivelEstudios_idNivelEstudios', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NivelEstudios.nivelestudios')),
            ],
            options={
                'db_table': 'formacionprofesional',
            },
        ),
    ]
