# Generated by Django 3.2.6 on 2021-09-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tipopersona', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipopersona',
            options={'verbose_name': 'Tipopersona', 'verbose_name_plural': 'Tipopersonas'},
        ),
    ]
