# Generated by Django 3.2.6 on 2021-10-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sector', '0003_alter_sector_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='idsector',
            field=models.AutoField(db_column='idSector', primary_key=True, serialize=False),
        ),
    ]
