# Generated by Django 3.2.6 on 2021-08-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estado', '0001_initial'),
        ('Tiposolicitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('idsolicitud', models.IntegerField(db_column='idSolicitud', primary_key=True, serialize=False)),
                ('profesion', models.CharField(blank=True, max_length=45, null=True)),
                ('aniosexperiencia', models.IntegerField(blank=True, db_column='aniosExperiencia', null=True)),
                ('rangoedad', models.CharField(blank=True, db_column='rangoEdad', max_length=45, null=True)),
                ('experticia', models.CharField(blank=True, max_length=45, null=True)),
                ('sueldo', models.FloatField(blank=True, null=True)),
                ('fechainicio', models.DateTimeField(blank=True, db_column='fechaInicio', null=True)),
                ('fechacierre', models.DateTimeField(blank=True, db_column='fechaCierre', null=True)),
                ('cargo', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcioncargo', models.CharField(blank=True, db_column='descripcionCargo', max_length=200, null=True)),
                ('estado_idestado', models.ForeignKey(db_column='Estado_idEstado', on_delete=django.db.models.deletion.DO_NOTHING, to='Estado.estado')),
                ('tiposolicitud_idtiposolicitud', models.ForeignKey(db_column='TipoSolicitud_idTipoSolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='Tiposolicitud.tiposolicitud')),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
    ]
