# Generated by Django 3.2.7 on 2021-10-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='discapacidad',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='disponibilidad_cambioresidencia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='disponibilidad_viajar',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='educacion_minima',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcioncargo',
            field=models.TextField(blank=True, db_column='descripcionCargo', null=True),
        ),
    ]
