# Generated by Django 3.2.6 on 2021-10-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Provincia', '0003_alter_provincia_nombreprovincia'),
        ('Empresa', '0004_auto_20210928_1257'),
        ('Usuario', '0003_auto_20210928_1431'),
        ('Ciudad', '0003_alter_ciudad_nombreciudad'),
        ('Solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicituds'},
        ),
        migrations.AddField(
            model_name='solicitud',
            name='ciudad_idciudad',
            field=models.ForeignKey(db_column='ciudad_idCiudad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Ciudad.ciudad'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='empresa_idempresa',
            field=models.ForeignKey(db_column='Empresa_idEmpresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Empresa.empresa'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='provincia_idprovincia',
            field=models.ForeignKey(db_column='provincia_idProvincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Provincia.provincia'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario_idusuario',
            field=models.ForeignKey(db_column='Usuario_idUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Usuario.usuario'),
        ),
    ]
