# Generated by Django 3.2.7 on 2021-10-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitud', '0002_auto_20211027_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='jornada',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
