# Generated by Django 3.2.7 on 2021-10-01 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tiposolicitud', '0002_alter_tiposolicitud_options'),
        ('Estado', '0002_alter_estado_options'),
        ('Solicitud', '0002_auto_20211001_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado_idestado',
            field=models.ForeignKey(db_column='Estado_idEstado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Estado.estado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tiposolicitud_idtiposolicitud',
            field=models.ForeignKey(db_column='TipoSolicitud_idTipoSolicitud', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Tiposolicitud.tiposolicitud'),
        ),
    ]
