# Generated by Django 3.2.7 on 2021-10-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitud', '0003_solicitud_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='idiomas',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='licencia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
