# Generated by Django 3.2.7 on 2021-10-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitud', '0004_auto_20211027_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
