# Generated by Django 3.2.6 on 2021-10-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitud', '0005_auto_20211005_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='idsolicitud',
            field=models.AutoField(db_column='idSolicitud', primary_key=True, serialize=False),
        ),
    ]
