# Generated by Django 3.2.7 on 2021-11-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitud', '0009_auto_20211104_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='disponibilidad_cambioresidencia',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='disponibilidad_viajar',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='posibilidadcambioresidencia',
            field=models.CharField(blank=True, db_column='posibilidadCambioResidencia', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='posibilidadviajar',
            field=models.CharField(blank=True, db_column='posibilidadViajar', max_length=5, null=True),
        ),
    ]
