# Generated by Django 3.2.7 on 2021-11-05 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NivelEstudios', '0001_initial'),
        ('Solicitud', '0010_auto_20211104_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='educacion_minima',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nivelestudios_idnivelestudios',
            field=models.ForeignKey(db_column='NivelEstudios_idNivelEstudios', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NivelEstudios.nivelestudios'),
        ),
    ]
