# Generated by Django 3.2.7 on 2021-10-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estado', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquetepago',
            fields=[
                ('idpaquetepago', models.IntegerField(db_column='idPaquetePago', primary_key=True, serialize=False)),
                ('nombrepaquete', models.CharField(blank=True, db_column='nombrePaquete', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('duracion', models.TimeField(blank=True, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('fechacaducidad', models.DateTimeField(blank=True, db_column='fechaCaducidad', null=True)),
                ('estado_idestado', models.ForeignKey(db_column='Estado_idEstado', on_delete=django.db.models.deletion.DO_NOTHING, to='Estado.estado')),
                ('usuario_idusuario', models.ForeignKey(db_column='Usuario_idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuario.usuario')),
            ],
            options={
                'db_table': 'paquetepago',
            },
        ),
    ]
