# Generated by Django 3.2.7 on 2021-12-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paquetepago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetepago',
            name='idpaquetepago',
            field=models.AutoField(db_column='idPaquetePago', primary_key=True, serialize=False),
        ),
    ]
