# Generated by Django 3.2.7 on 2021-12-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paquetepago', '0002_alter_paquetepago_idpaquetepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetepago',
            name='fechacaducidad',
            field=models.DateField(blank=True, db_column='fechaCaducidad', null=True),
        ),
        migrations.AlterField(
            model_name='paquetepago',
            name='fecharegistro',
            field=models.DateField(blank=True, db_column='fechaRegistro', null=True),
        ),
    ]
