# Generated by Django 3.2.7 on 2021-12-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paquetepago', '0004_alter_paquetepago_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetepago',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paquetepago',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
