# Generated by Django 3.2.7 on 2021-12-27 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DuracionPaquetes', '0001_initial'),
        ('Paquetepago', '0005_auto_20211220_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquetepago',
            name='duracion',
        ),
        migrations.AddField(
            model_name='paquetepago',
            name='duracionpaquetes_idduracionpaquetes',
            field=models.ForeignKey(db_column='DuracionPaquetes_idDuracionPaquetes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DuracionPaquetes.duracionpaquetes'),
        ),
    ]
