# Generated by Django 3.2.6 on 2021-10-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_auto_20211003_1659'),
        ('CategoriaDocumento', '0001_initial'),
        ('Aspirante', '0006_alter_aspirante_videopresentacion'),
        ('ArchivosAspirante', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='archivosAspirantes',
            new_name='ArchivosAspirante',
        ),
    ]
