# Generated by Django 3.2.7 on 2021-12-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArchivosAspirante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosaspirante',
            name='fechacreacion',
            field=models.DateTimeField(blank=True, db_column='fechaCreacion', null=True),
        ),
    ]
