# Generated by Django 3.2.7 on 2021-12-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArchivosAspirante', '0002_alter_archivosaspirante_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosaspirante',
            name='fechacreacion',
            field=models.DateField(blank=True, db_column='fechaCreacion', null=True),
        ),
    ]
