# Generated by Django 3.2.7 on 2021-10-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.AutoField(db_column='idEstado', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
            },
        ),
    ]
