# Generated by Django 3.2.6 on 2021-10-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
    ]
