# Generated by Django 3.2.6 on 2021-10-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estado', '0002_alter_estado_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='idestado',
            field=models.AutoField(db_column='idEstado', primary_key=True, serialize=False),
        ),
    ]
