# Generated by Django 3.2.6 on 2021-09-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ramaactividad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ramaactividad',
            options={'verbose_name': 'Ramaactividad', 'verbose_name_plural': 'Ramaactividads'},
        ),
    ]
