# Generated by Django 3.2.7 on 2021-10-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Provincia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idciudad', models.AutoField(db_column='idCiudad', primary_key=True, serialize=False)),
                ('nombreciudad', models.CharField(db_column='nombreCiudad', max_length=45, null=True, unique=True)),
                ('provincia_idprovincia', models.ForeignKey(db_column='Provincia_idProvincia', on_delete=django.db.models.deletion.DO_NOTHING, to='Provincia.provincia')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
            },
        ),
    ]
