# Generated by Django 3.2.6 on 2021-09-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ciudad', '0002_alter_ciudad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombreciudad',
            field=models.CharField(db_column='nombreCiudad', max_length=45, null=True, unique=True),
        ),
    ]
