# Generated by Django 3.2.6 on 2021-08-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representanteempresa',
            fields=[
                ('idrepresentanteempresa', models.IntegerField(db_column='idRepresentanteEmpresa', primary_key=True, serialize=False)),
                ('empresa_idempresa', models.ForeignKey(db_column='Empresa_idEmpresa', on_delete=django.db.models.deletion.DO_NOTHING, to='Empresa.empresa')),
                ('usuario_idusuario', models.ForeignKey(db_column='Usuario_idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuario.usuario')),
            ],
            options={
                'db_table': 'representanteempresa',
            },
        ),
    ]
