# Generated by Django 3.2.7 on 2021-10-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Representanteempresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representanteempresa',
            name='idrepresentanteempresa',
            field=models.AutoField(db_column='idRepresentanteEmpresa', primary_key=True, serialize=False),
        ),
    ]
