# Generated by Django 3.2.7 on 2021-10-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('idcategoriadocumento', models.AutoField(db_column='idCategoriaDocumento', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoriadocumento',
                'verbose_name_plural': 'Categoriadocumento',
                'db_table': 'categoriadocumento',
            },
        ),
    ]
