# Generated by Django 3.2.6 on 2021-08-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tipopersona', '0001_initial'),
        ('Actividadeconomica', '0001_initial'),
        ('Tipodocumento', '0001_initial'),
        ('Sector', '0001_initial'),
        ('Tipoempresa', '0001_initial'),
        ('Ramaactividad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.IntegerField(db_column='idEmpresa', primary_key=True, serialize=False)),
                ('ruc_cedula', models.CharField(blank=True, db_column='ruc/cedula', max_length=45, null=True)),
                ('nombrecomercial', models.CharField(blank=True, db_column='nombreComercial', max_length=45, null=True)),
                ('razonsocial', models.CharField(blank=True, db_column='razonSocial', max_length=45, null=True)),
                ('calleprincipal', models.CharField(blank=True, db_column='callePrincipal', max_length=45, null=True)),
                ('callesecundaria', models.CharField(blank=True, db_column='calleSecundaria', max_length=45, null=True)),
                ('mz', models.CharField(blank=True, max_length=45, null=True)),
                ('villa', models.CharField(blank=True, max_length=45, null=True)),
                ('referencia', models.CharField(blank=True, max_length=45, null=True)),
                ('telefonooficina', models.CharField(blank=True, db_column='telefonoOficina', max_length=45, null=True)),
                ('celular', models.CharField(blank=True, max_length=45, null=True)),
                ('correoelectronico', models.CharField(blank=True, db_column='correoElectronico', max_length=45, null=True)),
                ('paginaweb', models.CharField(blank=True, db_column='paginaWeb', max_length=45, null=True)),
                ('actividadeconomica_idactividadeconomica', models.ForeignKey(db_column='actividadEconomica_idactividadEconomica', on_delete=django.db.models.deletion.DO_NOTHING, to='Actividadeconomica.actividadeconomica')),
                ('ramaactividad_idramaactividad', models.ForeignKey(db_column='ramaActividad_idramaActividad', on_delete=django.db.models.deletion.DO_NOTHING, to='Ramaactividad.ramaactividad')),
                ('sector_idsector', models.ForeignKey(db_column='Sector_idSector', on_delete=django.db.models.deletion.DO_NOTHING, to='Sector.sector')),
                ('tipodocumento_idtipodocumento', models.ForeignKey(db_column='tipoDocumento_idtipoDocumento', on_delete=django.db.models.deletion.DO_NOTHING, to='Tipodocumento.tipodocumento')),
                ('tipoempresa_idtipoempresa', models.ForeignKey(db_column='tipoEmpresa_idtipoEmpresa', on_delete=django.db.models.deletion.DO_NOTHING, to='Tipoempresa.tipoempresa')),
                ('tipopersona_idtipopersona', models.ForeignKey(db_column='tipoPersona_idtipoPersona', on_delete=django.db.models.deletion.DO_NOTHING, to='Tipopersona.tipopersona')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
