# Generated by Django 3.2.6 on 2021-09-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
