# Generated by Django 3.2.7 on 2021-10-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='correoelectronico',
        ),
        migrations.AddField(
            model_name='empresa',
            name='correo',
            field=models.CharField(db_column='correo', max_length=45, null=True, unique=True),
        ),
    ]
