# Generated by Django 3.2.6 on 2021-09-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_empresa_contrasenia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correoelectronico',
            field=models.CharField(db_column='correoElectronico', max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruc_cedula',
            field=models.CharField(db_column='ruc/cedula', max_length=45, null=True, unique=True),
        ),
    ]
