# Generated by Django 3.2.7 on 2021-11-24 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estado', '0001_initial'),
        ('Empresa', '0002_auto_20211029_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estado_idestado',
            field=models.ForeignKey(db_column='Estado_idEstado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Estado.estado'),
        ),
    ]
