# Generated by Django 3.2.6 on 2021-09-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ciudad', '0003_alter_ciudad_nombreciudad'),
        ('Provincia', '0003_alter_provincia_nombreprovincia'),
        ('Sector', '0003_alter_sector_descripcion'),
        ('Empresa', '0003_auto_20210927_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciudad_idciudad',
            field=models.ForeignKey(db_column='ciudad_idCiudad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Ciudad.ciudad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='provincia_idprovincia',
            field=models.ForeignKey(db_column='provincia_idProvincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Provincia.provincia'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='sector_idsector',
            field=models.ForeignKey(db_column='sector_idSector', on_delete=django.db.models.deletion.DO_NOTHING, to='Sector.sector'),
        ),
    ]
