# Generated by Django 3.2.6 on 2021-10-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0005_auto_20211001_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='idempresa',
            field=models.AutoField(db_column='idEmpresa', primary_key=True, serialize=False),
        ),
    ]
