# Generated by Django 3.2.6 on 2021-09-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tipodocumento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'verbose_name': 'Tipodocumento', 'verbose_name_plural': 'Tipodocumentos'},
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='descripcion',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
