# Generated by Django 3.2.7 on 2022-01-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAspiranteEmpresa',
            fields=[
                ('idestadoaspiranteempresa', models.AutoField(db_column='idEstadoAspiranteEmpresa', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'EstadoAspiranteEmpresa',
                'verbose_name_plural': 'EstadoAspiranteEmpresa',
                'db_table': 'EstadoAspiranteEmpresa',
            },
        ),
    ]
