# Generated by Django 3.2.6 on 2021-08-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('idsugerencia', models.IntegerField(db_column='idSugerencia', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('usuario_idusuario', models.ForeignKey(db_column='Usuario_idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='Usuario.usuario')),
            ],
            options={
                'db_table': 'sugerencia',
            },
        ),
    ]
