# Generated by Django 3.2.7 on 2021-10-01 21:53

import applications.Sugerencia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sugerencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugerencia',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='idsugerencia',
            field=models.AutoField(db_column='idSugerencia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=applications.Sugerencia.models.nameFile),
        ),
    ]
