# Generated by Django 3.2.6 on 2021-11-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sugerencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
