# Generated by Django 3.2.7 on 2021-10-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sugerencia', '0002_auto_20211001_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='titulo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
