# Generated by Django 3.2.7 on 2021-10-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesiones',
            fields=[
                ('idprofesiones', models.AutoField(db_column='idProfesiones', primary_key=True, serialize=False)),
                ('profesion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'profesiones',
            },
        ),
    ]
