# Generated by Django 3.2.6 on 2021-10-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesiones',
            name='idprofesiones',
            field=models.AutoField(db_column='idProfesiones', primary_key=True, serialize=False),
        ),
    ]
