# Generated by Django 3.2.7 on 2021-10-26 06:25

import applications.Aspirante.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profesiones', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('idaspirante', models.AutoField(db_column='idAspirante', primary_key=True, serialize=False)),
                ('numerohijos', models.IntegerField(blank=True, db_column='numeroHijos', null=True)),
                ('experiencialaboral', models.CharField(blank=True, db_column='experienciaLaboral', max_length=45, null=True)),
                ('campolaboral', models.CharField(blank=True, db_column='campoLaboral', max_length=45, null=True)),
                ('experticia', models.CharField(blank=True, max_length=45, null=True)),
                ('videopresentacion', models.FileField(blank=True, null=True, upload_to=applications.Aspirante.models.nameFile)),
                ('aniosexperiencia', models.IntegerField(blank=True, db_column='aniosExperiencia', null=True)),
                ('fechanacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('posibilidadviajar', models.IntegerField(blank=True, db_column='posibilidadViajar', null=True)),
                ('profesiones_idprofesiones', models.ForeignKey(db_column='Profesiones_idProfesiones', on_delete=django.db.models.deletion.DO_NOTHING, to='Profesiones.profesiones')),
                ('usuario_idusuario', models.ForeignKey(db_column='usuario_idusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Usuario.usuario')),
            ],
            options={
                'db_table': 'aspirante',
            },
        ),
    ]
