# Generated by Django 3.2.6 on 2021-09-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='aspirantessolicitados_idaspirantessolicitados',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='profesion',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='solicitud_idsolicitud',
        ),
    ]
