# Generated by Django 3.2.6 on 2021-10-02 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_auto_20210928_1431'),
        ('Aspirante', '0002_auto_20210926_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='usuario_idusuario',
            field=models.ForeignKey(db_column='usuario_idusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Usuario.usuario'),
        ),
    ]
