# Generated by Django 3.2.7 on 2021-11-04 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NivelEstudios', '0001_initial'),
        ('Aspirante', '0003_auto_20211103_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='estadoestudios',
            field=models.CharField(blank=True, db_column='estadoEstudios', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='nivelestudios_idnivelestudios',
            field=models.ForeignKey(db_column='NivelEstudios_idNivelEstudios', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NivelEstudios.nivelestudios'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='posibilidadcambioresidencia',
            field=models.CharField(blank=True, db_column='posibilidadCambioResidencia', max_length=5, null=True),
        ),
    ]
