# Generated by Django 3.2.6 on 2021-10-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0003_aspirante_usuario_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='videopresentacion',
            field=models.FileField(blank=True, db_column='videoPresentacion', null=True, upload_to=''),
        ),
    ]
