# Generated by Django 3.2.6 on 2021-11-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0004_auto_20211104_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='idiomas',
            field=models.CharField(blank=True, db_column='idiomas', max_length=500, null=True),
        ),
    ]
