# Generated by Django 3.2.6 on 2021-10-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0004_alter_aspirante_videopresentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='idaspirante',
            field=models.AutoField(db_column='idAspirante', primary_key=True, serialize=False),
        ),
    ]
