# Generated by Django 3.2.7 on 2021-10-04 18:03

import applications.Aspirante.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0005_alter_aspirante_idaspirante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='videopresentacion',
            field=models.FileField(blank=True, null=True, upload_to=applications.Aspirante.models.nameFile),
        ),
    ]
