# Generated by Django 3.2.6 on 2021-11-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0005_aspirante_idiomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='estadoestudios',
            field=models.CharField(blank=True, db_column='estadoEstudios', max_length=50, null=True),
        ),
    ]
