# Generated by Django 3.2.7 on 2021-12-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0006_alter_aspirante_estadoestudios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='campolaboral',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='estadoestudios',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='experiencialaboral',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='experticia',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='nivelestudios_idnivelestudios',
        ),
        migrations.AddField(
            model_name='aspirante',
            name='descripcionPerfilProfesional',
            field=models.CharField(blank=True, db_column='descripcionPerfilProfesional', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='salarioMinimoAceptado',
            field=models.IntegerField(blank=True, db_column='salarioMinimoAceptado', null=True),
        ),
    ]
