# Generated by Django 3.2.7 on 2021-12-09 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EstadoAspirantes', '0001_initial'),
        ('Aspirante', '0007_auto_20211201_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='estadoaspirantes',
            field=models.ForeignKey(db_column='estadoaspirantes_idestadoaspirantes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='EstadoAspirantes.estadoaspirantes'),
        ),
    ]
