# Generated by Django 3.2.7 on 2021-12-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0008_aspirante_estadoaspirantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aspirante',
            old_name='estadoaspirantes',
            new_name='estadoaspirantes_idestadoaspirantes',
        ),
    ]
