# Generated by Django 3.2.7 on 2021-10-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idprovincia', models.AutoField(db_column='idProvincia', primary_key=True, serialize=False)),
                ('nombreprovincia', models.CharField(db_column='nombreProvincia', max_length=45, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
            },
        ),
    ]
