# Generated by Django 3.2.6 on 2021-08-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idprovincia', models.IntegerField(db_column='idProvincia', primary_key=True, serialize=False)),
                ('nombreprovincia', models.CharField(blank=True, db_column='nombreProvincia', max_length=45, null=True)),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
    ]
