# Generated by Django 3.2.6 on 2021-09-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Provincia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
    ]
