# Generated by Django 3.2.6 on 2021-10-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provincia', '0003_alter_provincia_nombreprovincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='idprovincia',
            field=models.AutoField(db_column='idProvincia', primary_key=True, serialize=False),
        ),
    ]
