# Generated by Django 3.2.7 on 2021-10-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiposolicitud',
            fields=[
                ('idtiposolicitud', models.IntegerField(db_column='idTipoSolicitud', primary_key=True, serialize=False)),
                ('descrpcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Tiposolicitud',
                'verbose_name_plural': 'Tiposolicituds',
                'db_table': 'tiposolicitud',
            },
        ),
    ]
