# Generated by Django 3.2.6 on 2021-10-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tiposolicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposolicitud',
            options={'verbose_name': 'Tiposolicitud', 'verbose_name_plural': 'Tiposolicituds'},
        ),
    ]
