# Generated by Django 3.2.7 on 2021-10-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Solicitud', '0001_initial'),
        ('Estado', '0001_initial'),
        ('Aspirante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirantessolicitados',
            fields=[
                ('idaspirantessolicitados', models.AutoField(db_column='idAspirantesSolicitados', primary_key=True, serialize=False)),
                ('fechaaceptacion', models.DateTimeField(blank=True, db_column='fechaAceptacion', null=True)),
                ('aspirante_idaspirante', models.ForeignKey(db_column='Aspirante_idaspirante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aspirante.aspirante')),
                ('estado_idestado', models.ForeignKey(db_column='Estado_idEstado', on_delete=django.db.models.deletion.DO_NOTHING, to='Estado.estado')),
                ('solicitud_idsolicitud', models.ForeignKey(db_column='Solicitud_idSolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitud.solicitud')),
            ],
            options={
                'db_table': 'aspirantessolicitados',
                'unique_together': {('idaspirantessolicitados', 'estado_idestado')},
            },
        ),
    ]
