# Generated by Django 3.2.6 on 2021-10-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirantessolicitados', '0002_aspirantessolicitados_aspirante_idaspirante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirantessolicitados',
            name='idaspirantessolicitados',
            field=models.AutoField(db_column='idAspirantesSolicitados', primary_key=True, serialize=False),
        ),
    ]
