# Generated by Django 3.2.6 on 2021-08-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadocivil',
            fields=[
                ('idestadocivil', models.IntegerField(db_column='idEstadoCivil', primary_key=True, serialize=False)),
                ('estadocivil', models.CharField(blank=True, db_column='estadoCivil', max_length=45, null=True)),
            ],
            options={
                'db_table': 'estadocivil',
            },
        ),
    ]
