# Generated by Django 3.2.6 on 2021-10-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estadocivil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'verbose_name': 'Estadocivil', 'verbose_name_plural': 'Estadocivils'},
        ),
    ]
