# Generated by Django 3.2.6 on 2021-10-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tipoempresa', '0002_auto_20210927_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoempresa',
            name='idtipoempresa',
            field=models.AutoField(db_column='idtipoEmpresa', primary_key=True, serialize=False),
        ),
    ]
