# Generated by Django 3.2.6 on 2021-08-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idgenero', models.IntegerField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'genero',
            },
        ),
    ]
