# Generated by Django 3.2.6 on 2021-08-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estadocivil', '0001_initial'),
        ('Rol', '0001_initial'),
        ('Ciudad', '0001_initial'),
        ('Solicitud', '0001_initial'),
        ('Provincia', '0001_initial'),
        ('Genero', '0001_initial'),
        ('Aspirante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(blank=True, db_column='nombreUsuario', max_length=45, null=True)),
                ('contrasenia', models.CharField(blank=True, max_length=16, null=True)),
                ('cedula', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('estadocuenta', models.CharField(blank=True, db_column='estadoCuenta', max_length=45, null=True)),
                ('aspirante_idaspirante', models.ForeignKey(db_column='Aspirante_idAspirante', on_delete=django.db.models.deletion.DO_NOTHING, to='Aspirante.aspirante')),
                ('ciudad_idciudad', models.ForeignKey(db_column='Ciudad_idCiudad', on_delete=django.db.models.deletion.DO_NOTHING, to='Ciudad.ciudad')),
                ('estadocivil_idestadocivil', models.ForeignKey(db_column='EstadoCivil_idEstadoCivil', on_delete=django.db.models.deletion.DO_NOTHING, to='Estadocivil.estadocivil')),
                ('genero_idgenero', models.ForeignKey(db_column='Genero_idGenero', on_delete=django.db.models.deletion.DO_NOTHING, to='Genero.genero')),
                ('provincia_idprovincia', models.ForeignKey(db_column='Provincia_idProvincia', on_delete=django.db.models.deletion.DO_NOTHING, to='Provincia.provincia')),
                ('rol_idrol', models.ForeignKey(db_column='Rol_idRol', on_delete=django.db.models.deletion.DO_NOTHING, to='Rol.rol')),
                ('solicitud_idsolicitud', models.ForeignKey(db_column='Solicitud_idSolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitud.solicitud')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
