# Generated by Django 3.2.6 on 2021-09-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='aspirante_idaspirante',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='solicitud_idsolicitud',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idusuario',
            field=models.AutoField(db_column='idUsuario', primary_key=True, serialize=False),
        ),
    ]
