# Generated by Django 3.2.6 on 2021-11-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nodocumento',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
