# Generated by Django 3.2.6 on 2021-09-28 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tipodocumento', '0002_auto_20210927_1817'),
        ('Usuario', '0002_auto_20210926_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cedula',
            new_name='nodocumento',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipodocumento_idtipodocumento',
            field=models.ForeignKey(db_column='tipodocumento_idtipodocumento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Tipodocumento.tipodocumento'),
        ),
    ]
