# Generated by Django 3.2.6 on 2021-10-03 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ciudad', '0003_alter_ciudad_nombreciudad'),
        ('Estado', '0003_alter_estado_idestado'),
        ('Provincia', '0003_alter_provincia_nombreprovincia'),
        ('Genero', '0002_alter_genero_options'),
        ('Estadocivil', '0002_alter_estadocivil_options'),
        ('Usuario', '0003_auto_20210928_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estadocuenta',
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_idestado',
            field=models.ForeignKey(db_column='estadoCuenta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Estado.estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad_idciudad',
            field=models.ForeignKey(db_column='Ciudad_idCiudad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Ciudad.ciudad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estadocivil_idestadocivil',
            field=models.ForeignKey(db_column='EstadoCivil_idEstadoCivil', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Estadocivil.estadocivil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero_idgenero',
            field=models.ForeignKey(db_column='Genero_idGenero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Genero.genero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='provincia_idprovincia',
            field=models.ForeignKey(db_column='Provincia_idProvincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Provincia.provincia'),
        ),
    ]
