# Generated by Django 3.2.7 on 2021-10-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_auto_20211012_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='last_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='first_name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
    ]
