# Generated by Django 3.2.7 on 2021-10-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0008_auto_20211012_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
    ]
