# Generated by Django 3.2.7 on 2021-10-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0009_remove_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
