# Generated by Django 3.2.7 on 2021-10-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0011_rename_contrasenia_usuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contrasenia',
        ),
    ]
