# Generated by Django 3.2.7 on 2021-10-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0013_rename_contrasenia_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
