# Generated by Django 3.2.7 on 2021-11-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEstudios',
            fields=[
                ('idnivelestudios', models.AutoField(db_column='idNivelEstudios', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'nivelEstudios',
                'verbose_name_plural': 'nivelEstudios',
                'db_table': 'nivelEstudion',
            },
        ),
    ]
